### ISSUE TITLE
Wrong disassembling of special mov (0xA0 and 0xA2)

### ISSUE THREAD

**Issue by Ch40zz** [rrrfff/LDasm#1]
Hey, just found a bug in this nice lib and wanted to tell you about it.
Disassembling 0xA0 or 0xA2 (mov al, byte ptr || mov byte ptr, al) returns the size 2 instead of 5 on x86 and 9 on x64.
You need to modify 2 places to fix it:

flags_table:
```
/* A0 */	OP_DATA_I16_I32_I64, // OP_DATA_I8
/* A1 */	OP_DATA_I16_I32_I64,
/* A2 */	OP_DATA_I16_I32_I64, // OP_DATA_I8
/* A3 */	OP_DATA_I16_I32_I64,
```

And parsing immediate data length on step 4:
```
/* phase 4: parse immediate data */
if ((rexw || (is64 && op >= 0xA0 && op <= 0xA3)) && f & OP_DATA_I16_I32_I64)
	ld->imm_size = 8;
else if (f & OP_DATA_I16_I32 || f & OP_DATA_I16_I32_I64)
	ld->imm_size = 4 - (pr_66 << 1);
```

Have a nice day :)

**Comment by Rprop** [comment]
fixed, thanks!
